### ISSUE TITLE
什么时候更新2019.1

### ISSUE THREAD

**Issue by mosesed** [xiaomao361/rdm#1]

**Comment by xiaomao361** [comment]
哈？出新版本啦，我去看下。

**Comment by xiaomao361** [comment]
这两天我尝试构建了下， 遇到了很多问题，现在的情况是这样的。
1. 官方的git 只保留了2019一个分支，并且里面的源码应该是多数都为2019.2~2019.3的一些future的功能，用该分支构建一直失败。
2. 我分别通过使用tag（2019.1）以及commit（36b60425106fed94995a9d9cbe691d399b1332ee）构建项目，是可以正常编译的，但是编译的结果版本显示还是2019.0.0，而且启动会弹窗提示要求更新到2019.1 并且强制退出，不知道是哪里出了问题。
ps： 并且我注意到，release列表里面 该tag（2019.1）是未验证状态的。

**Comment by xiaomao361** [comment]
进度更新：
通过提交issue，获得作者反馈后，通过修改rdm.pro文件，可以修改版本信息。
版本显示不对的问题已经解决。
现在编译没问题，但是通过QT运行的程序是可以使用的，单独双击bin文件，就一直打不开程序。
debug了下，接收到了崩溃的dump报告
```
Crash reason:  EXC_BREAKPOINT / EXC_I386_BPT
Crash address: 0x100462650
Process uptime: 1 seconds

Thread 0 (crashed)
 0  0x100462650
    rax = 0x0000000000000018   rdx = 0x00007ffeefbfbec0
    rcx = 0x0000000000000018   rbx = 0x00007fff4de43000
    rsi = 0x0000000000000001   rdi = 0x0000000000000000
    rbp = 0x00007ffeefbfbf70   rsp = 0x00007ffeefbfbeb8
     r8 = 0x0000000000000000    r9 = 0x0000000000000000
    r10 = 0x0000000000000000   r11 = 0x0000000000000000
    r12 = 0x00007ffeefbfbed0   r13 = 0x00007ffeefbfc760
    r14 = 0x0000000000000000   r15 = 0x0000000000000001
    rip = 0x0000000100462650
    Found by: given as instruction pointer in context
```
查了下好像是野指针的问题，暂时还没解决成功。

**Comment by xiaomao361** [comment]
> _No description provided._

更新了一个2019.2 可以看下。

**Comment by mosesed** [comment]
@xiaomao361 兄弟安装了,2019.02,打开的时候报错.
Process:               rdm [501]
Path:                  /Applications/rdm.app/Contents/MacOS/rdm
Identifier:            com.redisdesktop.rdm
Version:               2019.2
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           rdm [501]
User ID:               501

Date/Time:             2019-08-06 16:53:35.479 +0800
OS Version:            Mac OS X 10.14.6 (18G84)
Report Version:        12
Bridge OS Version:     3.0 (14Y904)

**Comment by xiaomao361** [comment]
> @xiaomao361 兄弟安装了,2019.02,打开的时候报错.
> Process: rdm [501]
> Path: /Applications/rdm.app/Contents/MacOS/rdm
> Identifier: com.redisdesktop.rdm
> Version: 2019.2
> Code Type: X86-64 (Native)
> Parent Process: ??? [1]
> Responsible: rdm [501]
> User ID: 501
> 
> Date/Time: 2019-08-06 16:53:35.479 +0800
> OS Version: Mac OS X 10.14.6 (18G84)
> Report Version: 12
> Bridge OS Version: 3.0 (14Y904)

好像出2019.3版本了，好频繁，我去看下，稍等。
ps：你的系统版本是？

**Comment by mosesed** [comment]
> > @xiaomao361 兄弟安装了,2019.02,打开的时候报错.
> > Process: rdm [501]
> > Path: /Applications/rdm.app/Contents/MacOS/rdm
> > Identifier: com.redisdesktop.rdm
> > Version: 2019.2
> > Code Type: X86-64 (Native)
> > Parent Process: ??? [1]
> > Responsible: rdm [501]
> > User ID: 501
> > Date/Time: 2019-08-06 16:53:35.479 +0800
> > OS Version: Mac OS X 10.14.6 (18G84)
> > Report Version: 12
> > Bridge OS Version: 3.0 (14Y904)
> 
> 好像出2019.3版本了，好频繁，我去看下，稍等。
> ps：你的系统版本是？

OS Version: 10.14.6 (18G87)

**Comment by xiaomao361** [comment]
> > > @xiaomao361 兄弟安装了,2019.02,打开的时候报错.
> > > Process: rdm [501]
> > > Path: /Applications/rdm.app/Contents/MacOS/rdm
> > > Identifier: com.redisdesktop.rdm
> > > Version: 2019.2
> > > Code Type: X86-64 (Native)
> > > Parent Process: ??? [1]
> > > Responsible: rdm [501]
> > > User ID: 501
> > > Date/Time: 2019-08-06 16:53:35.479 +0800
> > > OS Version: Mac OS X 10.14.6 (18G84)
> > > Report Version: 12
> > > Bridge OS Version: 3.0 (14Y904)
> > 
> > 
> > 好像出2019.3版本了，好频繁，我去看下，稍等。
> > ps：你的系统版本是？
> 
> OS Version: 10.14.6 (18G87)
啊...没仔细看，我的是10.14.6 (18G84)，我更新下，看看是不是这个问题导致的。

**Comment by xiaomao361** [comment]
> _No description provided._

更新了一个2019.3 看看打开可以使用吗？

**Comment by mosesed** [comment]
> > _No description provided._
> 
> 更新了一个2019.3 看看打开可以使用吗？

Dyld Error Message:
  Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Applications/rdm.app/Contents/MacOS/rdm
  Reason: image not found

**Comment by mosesed** [comment]
> > > _No description provided._
> > 
> > 
> > 更新了一个2019.3 看看打开可以使用吗？
> 
> Dyld Error Message:
> Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
> Referenced from: /Applications/rdm.app/Contents/MacOS/rdm
> Reason: image not found

装了python3可以了

**Comment by xiaomao361** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 更新了一个2019.3 看看打开可以使用吗？
> > 
> > 
> > Dyld Error Message:
> > Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
> > Referenced from: /Applications/rdm.app/Contents/MacOS/rdm
> > Reason: image not found
> 
> 装了python3可以了

奥，那是我的问题，会给app添加依赖的时候，好像python3没有添加进去，我去看下。
